## STEP 1: Import Libraries

In [1]:
import sqlite3
import pandas as pd
import numpy as np
from datetime import datetime

print("Libraries imported")

Libraries imported

## STEP 2: Load CSV file

In [4]:
data = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

## Create SQLite database

In [5]:
conn = sqlite3.connect("superstore.db")
cursor=conn.cursor()

## Loading Data into Table

In [7]:
# Creating table superstore
data.to_sql("superstore", conn, if_exists="replace", index=False)
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [41]:
print(""" BRIEF INSIGHTS!!
1. The Superstore dataset was successfully loaded into SQLite.
2. Storing data in a SQL database enables efficient querying, filtering, and analysis.""")

 BRIEF INSIGHTS!!
1. The Superstore dataset was successfully loaded into SQLite.
2. Storing data in a SQL database enables efficient querying, filtering, and analysis.

## STEP 2: Explore Table Schema

In [8]:
# query execution function
def run_query(query):
    return pd.read_sql(query,conn)

In [13]:
print("Schema")
q1= """
PRAGMA table_info(superstore);
"""
df_q1=run_query(q1)
df_q1

Schema

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity  INTEGER        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

In [42]:
print(""" BRIEF INSIGHTS!!
1. The schema provides information about available columns and their data types.
2.Understanding the schema helps in writing accurate SQL queries..""")

 BRIEF INSIGHTS!!
1. The schema provides information about available columns and their data types.
2.Understanding the schema helps in writing accurate SQL queries..

In [30]:
print("SAMPLE DATA ")
query = """
SELECT *
FROM superstore
LIMIT 8;
"""
pd.read_sql(query, conn)

SAMPLE DATA

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152

In [43]:
print(""" BRIEF INSIGHTS!!
1. Reviewing sample records helps verify that the dataset has been loaded correctly.
2. It provides an overview of customer, product, sales, and profit information..""")

 BRIEF INSIGHTS!!
1. Reviewing sample records helps verify that the dataset has been loaded correctly.
2. It provides an overview of customer, product, sales, and profit information..

In [12]:
print("TOTAL ROWS ")
query = """
SELECT COUNT(*) AS total_rows
FROM superstore;
"""
pd.read_sql(query, conn)

TOTAL ROWS

   total_rows
0        9994

In [44]:
print(""" BRIEF INSIGHTS!!
1. The row count confirms the size of the dataset.
2. This serves as a baseline for validating future query results.""")

 BRIEF INSIGHTS!!
1. The row count confirms the size of the dataset.
2. This serves as a baseline for validating future query results.

## STEP3. WHERE Filters

In [35]:
print("Filtering the rows by region as east")

query = """SELECT *
FROM superstore
WHERE Region = 'East'
"""
pd.read_sql(query, conn)

Filtering the rows by region as east

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,24,US-2017-156909,7/16/2017,7/18/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
1,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522
2,29,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,9.618,2,0.7,-7.0532
3,30,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.200,3,0.2,15.5250
4,31,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,3.264,2,0.2,1.1016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2843,9969,CA-2017-153871,12/11/2017,12/17/2017,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,...,7060,East,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,735.980,2,0.0,331.1910
2844,9970,CA-2017-153871,12/11/2017,12/17/2017,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,...,7060,East,OFF-AP-10003622,Office Supplies,Appliances,"Bravo II Megaboss 12-Amp Hard Body Upright, Re...",22.750,7,0.0,6.5975
2845,9982,CA-2017-163566,8/3/2017,8/6/2017,First Class,TB-21055,Ted Butterfield,Consumer,United States,Fairfield,...,45014,East,OFF-LA-10004484,Office Supplies,Labels,Avery 476,16.520,5,0.2,5.3690
2846,9985,CA-2015-100251,5/17/2015,5/23/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.500,10,0.0,15.1200
2847,9986,CA-2015-100251,5/17/2015,5/23/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.600,4,0.0,16.1240

In [45]:
print(""" BRIEF INSIGHTS!!
1. TThis filter isolates sales transactions from the East region.
2. It helps analyze regional sales performance.""")

 BRIEF INSIGHTS!!
1. TThis filter isolates sales transactions from the East region.
2. It helps analyze regional sales performance.

In [34]:
print("Filtering the rows by Category = Furniture")

query ="""SELECT *
FROM superstore
WHERE Category = 'Furniture'"""
pd.read_sql(query, conn)

Filtering the rows by Category = Furniture

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
4,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,9963,CA-2015-168088,3/19/2015,3/22/2015,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,77041,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
2117,9965,CA-2016-146374,12/5/2016,12/10/2016,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,FUR-FU-10002671,Furniture,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.4000,1,0.00,6.4320
2118,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
2119,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
2120,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332

In [46]:
print(""" BRIEF INSIGHTS!!
1. Furniture products can be analyzed separately from other categories.
2. Useful for understanding category-specific demand and profitability""")

 BRIEF INSIGHTS!!
1. Furniture products can be analyzed separately from other categories.
2. Useful for understanding category-specific demand and profitability

In [37]:
print("Filtering the rows by Sales > 1500")

query ="""SELECT *
FROM superstore
WHERE Sales > 1500"""
pd.read_sql(query, conn)

Filtering the rows by Sales > 1500

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092
1,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522
2,150,CA-2016-114489,12/5/2016,12/9/2016,Standard Class,JE-16165,Justin Ellison,Corporate,United States,Franklin,...,53132,Central,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",1951.840,8,0.0,585.5520
3,166,CA-2014-139892,9/8/2014,9/12/2014,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,...,78207,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,8159.952,8,0.4,-1359.9920
4,168,CA-2014-139892,9/8/2014,9/12/2014,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,...,78207,Central,FUR-CH-10004287,Furniture,Chairs,SAFCO Arco Folding Chair,1740.060,9,0.3,-24.8580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,9775,CA-2014-169019,7/26/2014,7/30/2014,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,...,78207,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,2177.584,8,0.8,-3701.8928
234,9858,CA-2015-164301,3/26/2015,3/30/2015,Standard Class,EB-13840,Ellis Ballard,Corporate,United States,Seattle,...,98103,West,FUR-TA-10001889,Furniture,Tables,Bush Advantage Collection Racetrack Conference...,3393.680,8,0.0,610.8624
235,9930,CA-2016-129630,9/4/2016,9/4/2016,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,94122,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.2,944.9865
236,9948,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464
237,9949,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,0.0,793.7160

In [47]:
print(""" Brief Insights!!! 
1. High-value transactions are identified.
2. These orders contribute significantly to overall revenue.""")

 Brief Insights!!!
1. High-value transactions are identified.
2. These orders contribute significantly to overall revenue.

In [38]:
print("Filtering the rows by Orders in 2015")

query= """SELECT *
FROM superstore
WHERE "Order Date" LIKE '%2015'"""
pd.read_sql(query, conn)

Filtering the rows by Orders in 2015

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
1,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
2,15,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580
3,16,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160
4,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097,9971,CA-2015-103772,6/28/2015,7/2/2015,Standard Class,MP-17470,Mark Packer,Home Office,United States,Smyrna,...,30080,South,OFF-BI-10002867,Office Supplies,Binders,GBC Recycled Regency Composition Covers,119.5600,2,0.00,54.9976
2098,9972,CA-2015-103772,6/28/2015,7/2/2015,Standard Class,MP-17470,Mark Packer,Home Office,United States,Smyrna,...,30080,South,OFF-AR-10000538,Office Supplies,Art,"Boston Model 1800 Electric Pencil Sharpener, Gray",140.7500,5,0.00,42.2250
2099,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
2100,9985,CA-2015-100251,5/17/2015,5/23/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.5000,10,0.00,15.1200
2101,9986,CA-2015-100251,5/17/2015,5/23/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.6000,4,0.00,16.1240

In [48]:
print(""" Brief Insights!!! 
1.Filtering by year helps analyze historical sales trends.
2. Useful for year-over-year performance comparisons..""")

 Brief Insights!!!
1.Filtering by year helps analyze historical sales trends.
2. Useful for year-over-year performance comparisons..

## STEP4: GROUP BY Aggregations

In [19]:
print("Grouping by Total Sales by Region ")
query = """SELECT Region,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY Region """

pd.read_sql(query, conn)

Grouping by Total Sales by Region

    Region  Total_Sales
0  Central    501239.89
1     East    678781.24
2    South    391721.91
3     West    725457.82

In [49]:
print(""" Brief Insights!!! 
1. Reveals which region generates the highest revenue.
2. Helps management focus on high-performing markets. """)

 Brief Insights!!!
1. Reveals which region generates the highest revenue.
2. Helps management focus on high-performing markets.

In [20]:
print("Grouping by Total Quantity by Category")
query = """SELECT Category,
       SUM(Quantity) AS Total_Quantity
FROM superstore
GROUP BY Category"""

pd.read_sql(query, conn)

Grouping by Total Quantity by Category

          Category  Total_Quantity
0        Furniture            8028
1  Office Supplies           22906
2       Technology            6939

In [21]:
print("Grouping by Average Profit by Category ")
query = """SELECT Category,
       ROUND(AVG(Profit),2) AS Avg_Profit
FROM superstore
GROUP BY Category"""

pd.read_sql(query, conn)

Grouping by Average Profit by Category

          Category  Avg_Profit
0        Furniture        8.70
1  Office Supplies       20.33
2       Technology       78.75

## STEP5: Sort and Limit Results

In [39]:
print(" Top 5 Products by Sales ")
query = """SELECT "Product Name",
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5 """

pd.read_sql(query, conn)

 Top 5 Products by Sales

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier     61599.82
1  Fellowes PB500 Electric Punch Plastic Comb Bin...     27453.38
2  Cisco TelePresence System EX90 Videoconferenci...     22638.48
3       HON 5400 Series Task Chairs for Big and Tall     21870.58
4         GBC DocuBind TL300 Electric Binding System     19823.48

In [50]:
print(""" Brief Insights!!! 
Highlights the highest revenue-generating products.
These products may require priority inventory management.""")

 Brief Insights!!!
Highlights the highest revenue-generating products.
These products may require priority inventory management.

In [23]:
print(" Top Categories by Profit ")
query = """SELECT Category,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Profit DESC"""

pd.read_sql(query, conn)

 Top Categories by Profit

          Category  Total_Profit
0       Technology     145454.95
1  Office Supplies     122490.80
2        Furniture      18451.27

# STEP 6: Business Use Cases

In [24]:
print("Monthly Sales Trend")
query = """SELECT SUBSTR("Order Date",-4) AS Year,
       SUBSTR("Order Date",1,2) AS Month,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY Year, Month
ORDER BY Year, Month"""

pd.read_sql(query, conn)

Monthly Sales Trend

    Year Month  Total_Sales
0   2014    1/     14236.90
1   2014    10     31453.39
2   2014    11     78628.72
3   2014    12     69545.62
4   2014    2/      4519.89
5   2014    3/     55691.01
6   2014    4/     28295.35
7   2014    5/     23648.29
8   2014    6/     34595.13
9   2014    7/     33946.39
10  2014    8/     27909.47
11  2014    9/     81777.35
12  2015    1/     18174.08
13  2015    10     31404.92
14  2015    11     75972.56
15  2015    12     74919.52
16  2015    2/     11951.41
17  2015    3/     38726.25
18  2015    4/     34195.21
19  2015    5/     30131.69
20  2015    6/     24797.29
21  2015    7/     28765.33
22  2015    8/     36898.33
23  2015    9/     64595.92
24  2016    1/     18542.49
25  2016    10     59687.75
26  2016    11     79411.97
27  2016    12     96999.04
28  2016    2/     22978.82
29  2016    3/     51715.88
30  2016    4/     38750.04
31  2016    5/     56987.73
32  2016    6/     40344.53
33  2016    7/     39261.96
34  2016    8/     31115.37
35  2016    9/     73410.02
36  2017    1/     43971.37
37  2017    10     77776.92
38  2017    11    118447.82
39  2017    12     83829.32
40  2017    2/     20301.13
41  2017    3/     58872.35
42  2017    4/     36521.54
43  2017    5/     44261.11
44  2017    6/     52981.73
45  2017    7/     45264.42
46  2017    8/     63120.89
47  2017    9/     87866.65

In [51]:
print(""" Brief Insights!!! 
Displays sales performance over time.
Helps identify seasonal demand patterns and growth trends.""")

 Brief Insights!!!
Displays sales performance over time.
Helps identify seasonal demand patterns and growth trends.

In [40]:
print("Top 5 Customers")
query = """SELECT "Customer Name",
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 5"""

pd.read_sql(query, conn)

Top 5 Customers

   Customer Name  Total_Sales
0    Sean Miller     25043.05
1   Tamara Chand     19052.22
2   Raymond Buch     15117.34
3   Tom Ashbrook     14595.62
4  Adrian Barton     14473.57

In [26]:
print("Find Duplicate Orders")

query = """SELECT "Order ID",
       COUNT(*) AS Duplicate_Count
FROM superstore
GROUP BY "Order ID"
HAVING COUNT(*) > 1 """

pd.read_sql(query, conn)

Find Duplicate Orders

            Order ID  Duplicate_Count
0     CA-2014-100090                2
1     CA-2014-100363                2
2     CA-2014-100678                4
3     CA-2014-100706                2
4     CA-2014-100762                4
...              ...              ...
2466  US-2017-168116                2
2467  US-2017-169320                2
2468  US-2017-169488                2
2469  US-2017-169502                2
2470  US-2017-169551                6

[2471 rows x 2 columns]

# STEP 7: Validate Results

In [27]:
print(" Null Values ")
query = """SELECT
COUNT(*) -
COUNT("Order ID") AS Missing_OrderID,
COUNT(*) -
COUNT(Sales) AS Missing_Sales
FROM superstore """

pd.read_sql(query, conn)

 Null Values

   Missing_OrderID  Missing_Sales
0                0              0

In [28]:
print("Row Count Check")
query = """SELECT COUNT(*) AS Total_Rows
FROM superstore """

pd.read_sql(query, conn)

Row Count Check

   Total_Rows
0        9994

In [52]:
print("""Brief Insights!!!
1. Confirms that no records were lost during data loading or transformation.
2. Ensures consistency throughout the analysis process.""")

Brief Insights!!!
1. Confirms that no records were lost during data loading or transformation.
2. Ensures consistency throughout the analysis process.

In [29]:
print("Distinct Customers")
query = """SELECT COUNT(DISTINCT "Customer ID") AS Total_Customers
FROM superstore """

pd.read_sql(query, conn)

Distinct Customers

   Total_Customers
0              793

In [53]:
print("""Brief Insights!!!
1. Shows the number of unique customers in the dataset.
2. Helps estimate customer base size and market reach.""")

Brief Insights!!!
1. Shows the number of unique customers in the dataset.
2. Helps estimate customer base size and market reach.