# STEP 1: Libraries Import

In [20]:
import sqlite3
import pandas as pd
import numpy as np

print("All libraries imported successfully")

All libraries imported successfully

# STEP 2: Database Connected

In [21]:
con = sqlite3.connect('superstore_db')
cursor = con.cursor()

# STEP 3: Creating Tables

### Table: Customers

In [11]:
cursor.execute('''
CREATE TABLE customers ( 
    customer_id   INT           PRIMARY KEY, 
    first_name    VARCHAR(50)   NOT NULL, 
    last_name     VARCHAR(50)   NOT NULL, 
    email         VARCHAR(100)  UNIQUE NOT NULL, 
    city          VARCHAR(50)   NOT NULL, 
    state         VARCHAR(50)   NOT NULL, 
    join_date     DATE          NOT NULL, 
    is_premium    BOOLEAN       DEFAULT FALSE 
)
''')

cursor.execute('''
CREATE INDEX idx_customers_city ON customers(city); 
''')
cursor.execute('''
CREATE INDEX idx_customers_state ON customers(state);
''')
con.commit()                                    
print("Customers Table Created!")

Customers Table Created!

### Table: Products

In [7]:
cursor.execute('''
CREATE TABLE products ( 
    product_id    INT           PRIMARY KEY, 
    product_name  VARCHAR(100)  NOT NULL, 
    category      VARCHAR(50)   NOT NULL, 
    brand         VARCHAR(50)   NOT NULL, 
    unit_price    DECIMAL(10,2) NOT NULL  CHECK (unit_price > 0), 
    stock_qty     INT           NOT NULL  DEFAULT 0  CHECK (stock_qty >= 0) 
)
''')

cursor.execute('''
CREATE INDEX idx_products_category ON products(category); 
''')
con.commit()                                    
print("Products Table Created!")

Products Table Created!

### Table: Orders

In [8]:
cursor.execute('''
CREATE TABLE orders ( 
    order_id      INT           PRIMARY KEY, 
    customer_id   INT           NOT NULL, 
    order_date    DATE          NOT NULL, 
    status        VARCHAR(20)   NOT NULL  DEFAULT 'Pending' 
                  CHECK (status IN ('Pending','Shipped','Delivered','Cancelled')), 
    total_amount  DECIMAL(12,2) NOT NULL  CHECK (total_amount >= 0), 
     
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) 
)
''')

cursor.execute('''
CREATE INDEX idx_orders_date ON orders(order_date); 
''')
cursor.execute('''
CREATE INDEX idx_orders_status ON orders(status);
''')
con.commit()                                    
print("Orders Table Created!")

Orders Table Created!

### Table: Order_Items

In [12]:
cursor.execute('''
CREATE TABLE order_items ( 
    item_id       INT           PRIMARY KEY, 
    order_id      INT           NOT NULL, 
    product_id    INT           NOT NULL, 
    quantity      INT           NOT NULL  CHECK (quantity > 0), 
    unit_price    DECIMAL(10,2) NOT NULL  CHECK (unit_price > 0), 
    discount_pct  DECIMAL(5,2)  DEFAULT 0 CHECK (discount_pct BETWEEN 0 AND 100), 
     
    FOREIGN KEY (order_id)   REFERENCES orders(order_id), 
    FOREIGN KEY (product_id) REFERENCES products(product_id) 
)
''')
con.commit()                                    
print("Order_Items Table Created!")

Order_Items Table Created!

# STEP 4: Inserting Data

### INSERT: customers

In [13]:
cursor.execute('''
INSERT INTO customers VALUES
(101, 'Aarav', 'Sharma', 'aarav.s@email.com', 'Mumbai', 'Maharashtra', '2024-01-15', TRUE),
(102, 'Priya', 'Patel', 'priya.p@email.com', 'Ahmedabad', 'Gujarat', '2024-02-20', FALSE),
(103, 'Rohan', 'Gupta', 'rohan.g@email.com', 'Delhi', 'Delhi', '2024-03-10', TRUE),
(104, 'Sneha', 'Reddy', 'sneha.r@email.com', 'Hyderabad', 'Telangana', '2024-04-05', FALSE),
(105, 'Vikram', 'Singh', 'vikram.s@email.com', 'Jaipur', 'Rajasthan', '2024-05-12', TRUE),
(106, 'Ananya', 'Iyer', 'ananya.i@email.com', 'Chennai', 'Tamil Nadu', '2024-06-18', FALSE),
(107, 'Karan', 'Mehta', 'karan.m@email.com', 'Pune', 'Maharashtra', '2024-07-22', TRUE),
(108, 'Divya', 'Nair', 'divya.n@email.com', 'Kochi', 'Kerala', '2024-08-30', FALSE)
''')

### INSERT: products

In [14]:
cursor.execute('''
INSERT INTO products VALUES 
(201, 'Wireless Earbuds',     'Electronics', 'BoAt',          1499.00, 250), 
(202, 'Cotton T-Shirt',       'Clothing',    'Levis',         799.00,  500), 
(203, 'Smart Watch',          'Electronics', 'Noise',         2999.00, 150), 
(204, 'Running Shoes',        'Clothing',    'Nike',          4599.00, 120), 
(205, 'Bluetooth Speaker',    'Electronics', 'JBL',           3499.00, 200), 
(206, 'Bedsheet Set',         'Home',        'Spaces',        1299.00, 300), 
(207, 'Laptop Stand',         'Electronics', 'AmazonBasics',  899.00,  180), 
(208, 'Cushion Covers (Set)', 'Home',        'HomeCenter',    599.00,  400);
''')

### INSERT: orders

In [15]:
cursor.execute('''
INSERT INTO orders VALUES 
(1001, 101, '2024-08-01', 'Delivered',  4498.00), 
(1002, 102, '2024-08-03', 'Delivered',  799.00), 
(1003, 103, '2024-08-05', 'Shipped',    7498.00), 
(1004, 101, '2024-08-10', 'Delivered',  3499.00), 
(1005, 104, '2024-08-12', 'Cancelled',  2999.00), 
(1006, 105, '2024-08-15', 'Delivered',  5898.00), 
(1007, 106, '2024-08-18', 'Pending',    1299.00), 
(1008, 103, '2024-08-20', 'Delivered',  899.00), 
(1009, 107, '2024-08-25', 'Shipped',    6098.00), 
(1010, 108, '2024-08-28', 'Delivered',  1598.00);
''')

### INSERT: orders_items

In [16]:
cursor.execute('''
INSERT INTO order_items VALUES 
(5001, 1001, 201, 2, 1499.00, 0), 
(5002, 1001, 207, 1, 899.00,  10), 
(5003, 1002, 202, 1, 799.00,  0), 
(5004, 1003, 203, 1, 2999.00, 0), 
(5005, 1003, 204, 1, 4599.00, 5), 
(5006, 1004, 205, 1, 3499.00, 0), 
(5007, 1005, 203, 1, 2999.00, 0), 
(5008, 1006, 201, 1, 1499.00, 10), 
(5009, 1006, 204, 1, 4599.00, 5), 
(5010, 1007, 206, 1, 1299.00, 0), 
(5011, 1008, 207, 1, 899.00,  0), 
(5012, 1009, 205, 1, 3499.00, 0), 
(5013, 1009, 208, 2, 599.00,  15), 
(5014, 1010, 206, 1, 1299.00, 0), 
(5015, 1010, 208, 1, 599.00,  0); 
''')

In [20]:
con.commit()
print("All data inserted successfully!")

All data inserted successfully!

# STEP 5:

## Section A — SQL Basics (SELECT, Constraints, Primary Keys)

In [2]:
# Helper Function
def run_query(query):
   return pd.read_sql_query(query,con)

### Q1. Write a query to display all columns and rows from the customer's table.

In [25]:
q1 = "SELECT * FROM customers"
df_q1 = run_query(q1)
df_q1

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

### Q2. Retrieve only the first_name, last_name, and city of all customers.

In [27]:
q2 = "SELECT first_name,last_name,last_name FROM customers"
df_q2 = run_query(q2)
df_q2

  first_name last_name last_name
0      Aarav    Sharma    Sharma
1      Priya     Patel     Patel
2      Rohan     Gupta     Gupta
3      Sneha     Reddy     Reddy
4     Vikram     Singh     Singh
5     Ananya      Iyer      Iyer
6      Karan     Mehta     Mehta
7      Divya      Nair      Nair

### Q3. List all unique categories available in the products table.

In [29]:
q3 = "SELECT DISTINCT(category) FROM products"
df_q3 = run_query(q3)
df_q3

      category
0     Clothing
1  Electronics
2         Home

### Q4. Identify the Primary Key of each table in the schema. Explain why a Primary Key must be unique and NOT NULL.

In [28]:
print(""" Table Name             Primary Key 

 customers    --->      customer_id 
 products     --->      product_id  
 orders       --->      order_id    
 order_items  --->      item_id   """)

print("""A Primary Key (PK) is a column or set of columns that uniquely identifies each record in a table.

A Primary Key be UNIQUE--
1. Every row in a table must be distinguishable from all other rows.
2. If duplicate primary key values exist, the database cannot identify which record is being referenced.
Example: Two customers cannot have the same customer_id.

A Primary Key be NOT NULL---
1. A primary key is used to identify a specific record.
2. A NULL value represents an unknown or missing value.
If a primary key were NULL, the database would not be able to uniquely identify that row.""")

 Table Name             Primary Key

 customers    --->      customer_id
 products     --->      product_id
 orders       --->      order_id
 order_items  --->      item_id
A Primary Key (PK) is a column or set of columns that uniquely identifies each record in a table.

A Primary Key be UNIQUE--
1. Every row in a table must be distinguishable from all other rows.
2. If duplicate primary key values exist, the database cannot identify which record is being referenced.
Example: Two customers cannot have the same customer_id.

A Primary Key be NOT NULL---
1. A primary key is used to identify a specific record.
2. A NULL value represents an unknown or missing value.
If a primary key were NULL, the database would not be able to uniquely identify that row.

### Q5. What constraints are applied to the email column in the customers table? What would happen if you tried to insert a duplicate email?

In [39]:
print("""The email column has the following constraints:

1. UNIQUE
Ensures that no two customers can have the same email address.
Each email must be distinct across all records.

2. NOT NULL
Prevents the email field from being left empty.
Every customer record must contain a valid email value.

If a Duplicate Email is Inserted then---
If you try to insert a customer with an email address that already exists in the table, 
the database will reject the insertion and return a UNIQUE constraint violation error.""")

The email column has the following constraints:

1. UNIQUE
Ensures that no two customers can have the same email address.
Each email must be distinct across all records.

2. NOT NULL
Prevents the email field from being left empty.
Every customer record must contain a valid email value.

If a Duplicate Email is Inserted then---
If you try to insert a customer with an email address that already exists in the table,
the database will reject the insertion and return a UNIQUE constraint violation error.

### Q6. Try inserting a product with unit_price = -50. What happens and which constraint prevents it? Write both the INSERT statement and explain the error.

In [40]:
cursor.execute("""INSERT INTO products
(product_id, product_name, category, brand, unit_price, stock_qty)
VALUES
(999, 'Test Product', 'Electronics', 'TestBrand', -50, 10)""")

IntegrityError: CHECK constraint failed: unit_price > 0

In [41]:
print("""The insertion fails because the value -50 violates the CHECK constraint defined on the unit_price column.
The database only allows values greater than 0 for unit_price.
Since -50 is less than 0, It rejects the row and does not insert it into the table.

The CHECK (unit_price > 0) constraint ensures data integrity by preventing invalid product prices such as negative values or zero prices
from being stored in the database.""")

The insertion fails because the value -50 violates the CHECK constraint defined on the unit_price column.
The database only allows values greater than 0 for unit_price.
Since -50 is less than 0, It rejects the row and does not insert it into the table.

The CHECK (unit_price > 0) constraint ensures data integrity by preventing invalid product prices such as negative values or zero prices
from being stored in the database.

# STEP 6:

## Section B — Filtering & Optimization (WHERE, Indexes)

### Q1. Retrieve all orders with status = 'Delivered'

In [33]:
q1 = "SELECT * FROM orders WHERE status = 'Delivered'"
df_q1 = run_query(q1)
df_q1

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered          4498
1      1002          102  2024-08-03  Delivered           799
2      1004          101  2024-08-10  Delivered          3499
3      1006          105  2024-08-15  Delivered          5898
4      1008          103  2024-08-20  Delivered           899
5      1010          108  2024-08-28  Delivered          1598

### Q2. Find all products in the 'Electronics' category with a unit_price greater than ₹2000.

In [35]:
q2 = "SELECT * FROM products WHERE category = 'Electronics' And unit_price > 2000"
df_q2 = run_query(q2)
df_q2

   product_id       product_name     category  brand  unit_price  stock_qty
0         203        Smart Watch  Electronics  Noise        2999        150
1         205  Bluetooth Speaker  Electronics    JBL        3499        200

### Q3. List all customers who joined in the year 2024 and belong to the state 'Maharashtra'.

In [39]:
q3 = "SELECT * FROM customers WHERE strftime('%Y', join_date) = '2024' AND state = 'Maharashtra'"
df_q3 = run_query(q3)
df_q3

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

### Q4. Find all orders placed between '2024-08-10' and '2024-08-25' (inclusive) that are NOT cancelled.

In [45]:
q4 = "SELECT * FROM orders where order_date BETWEEN '2024-08-10' AND '2024-08-25' AND status != 'cancelled'"
df_q4 = run_query(q4)
df_q4

   order_id  customer_id  order_date     status  total_amount
0      1004          101  2024-08-10  Delivered          3499
1      1005          104  2024-08-12  Cancelled          2999
2      1006          105  2024-08-15  Delivered          5898
3      1007          106  2024-08-18    Pending          1299
4      1008          103  2024-08-20  Delivered           899
5      1009          107  2024-08-25    Shipped          6098

### Q5. Explain what the index idx_orders_date does. How would it improve the performance of a query that filters orders by order_date? Write a sample query that would benefit from this index.

In [48]:
print("""
The index idx_orders_date creates a separate data structure that stores the values of the order_date column in a sorted format along with 
pointers to the corresponding rows in the orders table. This allows the database to quickly locate records based on order_date without
scanning the entire table.

It Improve Performance as--

Without the index:
The database performs a full table scan.
Every row in the orders table must be checked to find matching dates.
Performance becomes slower as the number of orders increases.

With the index:
The database can directly locate the required dates using the index.
Fewer rows need to be examined.
Queries run much faster, especially on large datasets""")

The index idx_orders_date creates a separate data structure that stores the values of the order_date column in a sorted format along with
pointers to the corresponding rows in the orders table. This allows the database to quickly locate records based on order_date without
scanning the entire table.

It Improve Performance as--

Without the index:
The database performs a full table scan.
Every row in the orders table must be checked to find matching dates.
Performance becomes slower as the number of orders increases.

With the index:
The database can directly locate the required dates using the index.
Fewer rows need to be examined.
Queries run much faster, especially on large datasets

In [52]:
print("SAMPLE QUERY THAT BENEFITS FROM THIS INDEX---")
query = "SELECT * FROM orders WHERE order_date BETWEEN '2024-08-01' AND '2024-08-10' "
df_query = run_query(query)
df_query

SAMPLE QUERY THAT BENEFITS FROM THIS INDEX---

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered          4498
1      1002          102  2024-08-03  Delivered           799
2      1003          103  2024-08-05    Shipped          7498
3      1004          101  2024-08-10  Delivered          3499

### Q6. If you run: SELECT * FROM customers WHERE YEAR(join_date) = 2024; — would the index on join_date be used? Explain why or why not, and rewrite the query to be index-friendly (SARGable).

In [54]:
print("""No, the index on join_date would generally not be used efficiently.
The query applies the function YEAR() to the indexed column join_date.

When a function is applied to an indexed column, the database must first calculate the function value for every row before comparing it to 2024.
This prevents the database from using the index effectively and often results in a full table scan.

-->Indexes work best when the database can directly search the indexed values.""")

print("""Index-Friendly (SARGable) Version

A SARGable query allows the database engine to use the index efficiently.
""")

q = """SELECT * FROM customers
WHERE join_date >= '2024-01-01'
  AND join_date < '2025-01-01' """
df_q = run_query(q)
df_q

No, the index on join_date would generally not be used efficiently.
The query applies the function YEAR() to the indexed column join_date.

When a function is applied to an indexed column, the database must first calculate the function value for every row before comparing it to 2024.
This prevents the database from using the index effectively and often results in a full table scan.

-->Indexes work best when the database can directly search the indexed values.
Index-Friendly (SARGable) Version

A SARGable query allows the database engine to use the index efficiently.

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

# STEP 7:

## Section C — Aggregation (GROUP BY, SUM, COUNT, AVG, MIN, MAX)

## Q1. Count the total number of orders in the orders table.

In [47]:
q1 = "SELECT COUNT(*) as Total_orders FROM orders"
df_q1 = run_query(q1)
df_q1

   Total_orders
0            10

### Q2. Find the total revenue (SUM of total_amount) from all 'Delivered' orders.

In [48]:
q2 = "SELECT SUM(total_amount) as Total_Revenue FROM orders WHERE status = 'Delivered'"
df_q2 = run_query(q2)
df_q2

   Total_Revenue
0          17191

### Q3. Calculate the average unit_price of products in each category.

In [50]:
q3 = "SELECT category,AVG(unit_price) as Average FROM products GROUP BY category"
df_q3 = run_query(q3)
df_q3

      category  Average
0     Clothing   2699.0
1  Electronics   2224.0
2         Home    949.0

### Q4. For each order status, find the count of orders and the total revenue. Sort the result by total revenue in descending order.

In [51]:
q4 = "SELECT status,count(order_id) as Total_Orders,SUM(total_amount) as Total_Revenue FROM orders GROUP BY status ORDER BY Total_Revenue DESC"
df_q4 = run_query(q4)
df_q4

      status  Total_Orders  Total_Revenue
0  Delivered             6          17191
1    Shipped             2          13596
2  Cancelled             1           2999
3    Pending             1           1299

### Q5. Find the most expensive (MAX) and cheapest (MIN) product in each category.

In [55]:
q5 = "SELECT category,MAX(unit_price) AS Expensive,MIN(unit_price) AS Cheapest FROM products GROUP BY category"
df_q5 = run_query(q5)
df_q5

      category  Expensive  Cheapest
0     Clothing       4599       799
1  Electronics       3499       899
2         Home       1299       599

### Q6. List all product categories where the average unit_price is greater than ₹2000.

In [55]:
q6 = "SELECT category,AVG(unit_price) AS Average FROM products GROUP BY category HAVING AVG(unit_price) > 2000 "
df_q6 = run_query(q6)
df_q6

      category  Average
0     Clothing   2699.0
1  Electronics   2224.0

# STEP 8:

## Section D — Joins & Relationships

### Q1. Write an INNER JOIN query to display each order along with the customer's first_name and last_name. Show: order_id, order_date, first_name, last_name, total_amount.

In [59]:
q1 = "SELECT o.order_id, o.order_date, c.first_name, c.last_name, o.total_amount FROM orders o INNER JOIN customers c ON c.customer_id = o.customer_id"
df_q1 = run_query(q1)
df_q1

   order_id  order_date first_name last_name  total_amount
0      1001  2024-08-01      Aarav    Sharma          4498
1      1002  2024-08-03      Priya     Patel           799
2      1003  2024-08-05      Rohan     Gupta          7498
3      1004  2024-08-10      Aarav    Sharma          3499
4      1005  2024-08-12      Sneha     Reddy          2999
5      1006  2024-08-15     Vikram     Singh          5898
6      1007  2024-08-18     Ananya      Iyer          1299
7      1008  2024-08-20      Rohan     Gupta           899
8      1009  2024-08-25      Karan     Mehta          6098
9      1010  2024-08-28      Divya      Nair          1598

### Q2. Using a LEFT JOIN, list ALL customers and their orders (if any). Customers with no orders should still appear with NULL values for order columns.

In [62]:
q2 = "SELECT * FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id"
df_q2 = run_query(q2)
df_q2

,customer_id,first_name,last_name,email,city,state,join_date,is_premium,order_id,customer_id,order_date,status,total_amount
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1,1001,101,2024-08-01,Delivered,4498
1,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1,1004,101,2024-08-10,Delivered,3499
2,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0,1002,102,2024-08-03,Delivered,799
3,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1,1003,103,2024-08-05,Shipped,7498
4,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1,1008,103,2024-08-20,Delivered,899
5,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0,1005,104,2024-08-12,Cancelled,2999
6,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1,1006,105,2024-08-15,Delivered,5898
7,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0,1007,106,2024-08-18,Pending,1299
8,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1,1009,107,2024-08-25,Shipped,6098
9,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0,1010,108,2024-08-28,Delivered,1598

### Q3. Write a query using JOINs across three tables (orders → order_items → products) to show: order_id, product_name, quantity, unit_price, and discount_pct for each order item.

In [65]:
q3 = "SELECT  o.order_id, p.product_name, oi.quantity, oi.unit_price,oi.discount_pct FROM orders o INNER JOIN order_items oi on o.order_id = oi.order_id INNER JOIN products p on oi.product_id = p.product_id"
df_q3 = run_query(q3)
df_q3

    order_id          product_name  quantity  unit_price  discount_pct
0       1001      Wireless Earbuds         2        1499             0
1       1001          Laptop Stand         1         899            10
2       1002        Cotton T-Shirt         1         799             0
3       1003           Smart Watch         1        2999             0
4       1003         Running Shoes         1        4599             5
5       1004     Bluetooth Speaker         1        3499             0
6       1005           Smart Watch         1        2999             0
7       1006      Wireless Earbuds         1        1499            10
8       1006         Running Shoes         1        4599             5
9       1007          Bedsheet Set         1        1299             0
10      1008          Laptop Stand         1         899             0
11      1009     Bluetooth Speaker         1        3499             0
12      1009  Cushion Covers (Set)         2         599            15
13      1010          Bedsheet Set         1        1299             0
14      1010  Cushion Covers (Set)         1         599             0

### Q4. Explain the difference between LEFT JOIN and RIGHT JOIN with an example from this schema. When would you use a FULL OUTER JOIN?

### LEFT JOIN

In [56]:
print("""A LEFT JOIN returns:
1. All records from the left table.
2. Matching records from the right table.
3. If there is no match, NULL values are returned for the right table columns. """)
print("  ")

print(" EXAMPLE OF LEFT JOIN---")
q = """SELECT c.customer_id,
       c.first_name,
       o.order_id,
       o.order_date
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id """
df = run_query(q)
df

A LEFT JOIN returns:
1. All records from the left table.
2. Matching records from the right table.
3. If there is no match, NULL values are returned for the right table columns.

 EXAMPLE OF LEFT JOIN---

   customer_id first_name  order_id  order_date
0          101      Aarav      1001  2024-08-01
1          101      Aarav      1004  2024-08-10
2          102      Priya      1002  2024-08-03
3          103      Rohan      1003  2024-08-05
4          103      Rohan      1008  2024-08-20
5          104      Sneha      1005  2024-08-12
6          105     Vikram      1006  2024-08-15
7          106     Ananya      1007  2024-08-18
8          107      Karan      1009  2024-08-25
9          108      Divya      1010  2024-08-28

### RIGHT JOIN

In [57]:
print("""
A RIGHT JOIN returns:
1. All records from the right table.
2. Matching records from the left table.
3. If there is no match, NULL values are returned for the left table columns.""")
print("  ")

print(" EXAMPLE OF RIGHT JOIN---")
q = """SELECT c.customer_id,
       c.first_name,
       o.order_id,
       o.order_date
FROM customers c
RIGHT JOIN orders o
ON c.customer_id = o.customer_id"""
df = run_query(q)
df

A RIGHT JOIN returns:
1. All records from the right table.
2. Matching records from the left table.
3. If there is no match, NULL values are returned for the left table columns.

 EXAMPLE OF RIGHT JOIN---

   customer_id first_name  order_id  order_date
0          101      Aarav      1001  2024-08-01
1          101      Aarav      1004  2024-08-10
2          102      Priya      1002  2024-08-03
3          103      Rohan      1003  2024-08-05
4          103      Rohan      1008  2024-08-20
5          104      Sneha      1005  2024-08-12
6          105     Vikram      1006  2024-08-15
7          106     Ananya      1007  2024-08-18
8          107      Karan      1009  2024-08-25
9          108      Divya      1010  2024-08-28

### Full Outer Join

In [61]:
print("""A FULL OUTER JOIN returns:
1. All rows from both tables.
2. Matching rows are combined.
3. Non-matching rows from either table are included with NULL values.

Example Scenario
Suppose you want:
All customers (even those with no orders)
All orders (even those with no valid customer)""")
print(" ")

print(" EXAMPLE OF FULL OUTER JOIN---")
q = """SELECT c.customer_id,
       c.first_name,
       o.order_id
FROM customers c
FULL OUTER JOIN orders o
ON c.customer_id = o.customer_id;"""
df = run_query(q)
df

A FULL OUTER JOIN returns:
1. All rows from both tables.
2. Matching rows are combined.
3. Non-matching rows from either table are included with NULL values.

Example Scenario
Suppose you want:
All customers (even those with no orders)
All orders (even those with no valid customer)

 EXAMPLE OF FULL OUTER JOIN---

   customer_id first_name  order_id
0          101      Aarav      1001
1          101      Aarav      1004
2          102      Priya      1002
3          103      Rohan      1003
4          103      Rohan      1008
5          104      Sneha      1005
6          105     Vikram      1006
7          106     Ananya      1007
8          107      Karan      1009
9          108      Divya      1010

### Q5. Identify all Foreign Key relationships in the schema. Explain what would happen if you tried to insert an order with customer_id = 999 (which doesn't exist in customers).

In [62]:
# order with customer_id = 999 (which doesn't exist in customers)
print("""
All foreign keys in schema are:\n
FOREIGN KEY (customer_id)
REFERENCES customers(customer_id)
FOREIGN KEY (order_id)
REFERENCES orders(order_id)
FOREIGN KEY (product_id)
REFERENCES products(product_id)

""")
print("""If I tried to insert an order with customer_id = 999 then:\n
The database will reject the insertion and raise a Foreign Key 
Constraint Violation error because the value 999 is not present in the parent table (customers)
""")

All foreign keys in schema are:

FOREIGN KEY (customer_id)
REFERENCES customers(customer_id)
FOREIGN KEY (order_id)
REFERENCES orders(order_id)
FOREIGN KEY (product_id)
REFERENCES products(product_id)


If I tried to insert an order with customer_id = 999 then:

The database will reject the insertion and raise a Foreign Key
Constraint Violation error because the value 999 is not present in the parent table (customers)

# STEP 9:

## Section E — Advanced Concepts (CASE, ACID, Transactions)

Q1. Write a query using CASE to classify products into price tiers: 
  • 'Budget'    → unit_price < 1000 
  • 'Mid-Range' → unit_price BETWEEN 1000 AND 3000 
  • 'Premium'   → unit_price > 3000 
Display: product_name, unit_price, price_tier.

In [6]:
q1 =  """SELECT product_name, unit_price,
       CASE 
           WHEN unit_price < 1000 THEN 'Budget'
           WHEN unit_price BETWEEN 1000 AND 3000 THEN 'Mid-Range'
           WHEN unit_price > 3000 THEN 'Premium'
       END as price_tier
FROM products 
ORDER BY unit_price"""
df_q1 = run_query(q1)
df_q1

           product_name  unit_price price_tier
0  Cushion Covers (Set)         599     Budget
1        Cotton T-Shirt         799     Budget
2          Laptop Stand         899     Budget
3          Bedsheet Set        1299  Mid-Range
4      Wireless Earbuds        1499  Mid-Range
5           Smart Watch        2999  Mid-Range
6     Bluetooth Speaker        3499    Premium
7         Running Shoes        4599    Premium

### Q2. Using a CASE statement inside an aggregate function, count how many orders are 'Delivered' vs 'Not Delivered' (all other statuses). Display the result in a single row.

In [7]:
q2 = """SELECT 
    SUM(CASE WHEN status = 'Delivered' THEN 1 ELSE 0 END) as delivered_count,
    SUM(CASE WHEN status != 'Delivered' THEN 1 ELSE 0 END) as not_delivered_count
FROM orders"""
df_q2 = run_query(q2)
df_q2

   delivered_count  not_delivered_count
0                6                    4

Q3. Explain each letter of ACID: 
  • A – Atomicity 
  • C – Consistency 
  • I – Isolation 
  • D – Durability 
Give a real-world example (e.g., bank transfer) showing why each property is important.

In [67]:
print("""ACID properties ensure that database transactions are processed reliably and safely.

--> A – ATOMICITY
A transaction is treated as a single unit of work. Either all operations succeed or none of them do.

Bank Transfer Example:
Suppose ₹1000 is transferred from Account A to Account B.
Deduct ₹1000 from Account A.
Add ₹1000 to Account B.

If the system crashes after step 1 but before step 2, Atomicity ensures the entire transaction is rolled back so no money is lost.""")
print("   ")

print("""--> C – CONSISTENCY
A transaction must take the database from one valid state to another valid state while following all rules and constraints.

Bank Transfer Example:
Before transfer:
Account A = ₹5000
Account B = ₹3000
Total = ₹8000

After transferring ₹1000:
Account A = ₹4000
Account B = ₹4000
Total = ₹8000

Consistency ensures the total balance remains correct.""")
print("   ")

print("""--> I – ISOLATION
Multiple transactions running at the same time should not interfere with each other.

Bank Transfer Example:
Two users try to withdraw money from the same account simultaneously.

Isolation ensures one transaction completes properly before another affects the same data, preventing incorrect balances.""")
print("   ")

print("""--> D – DURABILITY
Once a transaction is committed, its changes are permanently saved, even if the system crashes.

Bank Transfer Example:
After a successful transfer of ₹1000, the bank server suddenly crashes.

When the system restarts, the transfer remains recorded because the committed transaction was permanently stored.""")

ACID properties ensure that database transactions are processed reliably and safely.

--> A – ATOMICITY
A transaction is treated as a single unit of work. Either all operations succeed or none of them do.

Bank Transfer Example:
Suppose ₹1000 is transferred from Account A to Account B.
Deduct ₹1000 from Account A.
Add ₹1000 to Account B.

If the system crashes after step 1 but before step 2, Atomicity ensures the entire transaction is rolled back so no money is lost.

--> C – CONSISTENCY
A transaction must take the database from one valid state to another valid state while following all rules and constraints.

Bank Transfer Example:
Before transfer:
Account A = ₹5000
Account B = ₹3000
Total = ₹8000

After transferring ₹1000:
Account A = ₹4000
Account B = ₹4000
Total = ₹8000

Consistency ensures the total balance remains correct.

--> I – ISOLATION
Multiple transactions running at the same time should not interfere with each other.

Bank Transfer Example:
Two users try to withdraw money from the same account simultaneously.

Isolation ensures one transaction completes properly before another affects the same data, preventing incorrect balances.

--> D – DURABILITY
Once a transaction is committed, its changes are permanently saved, even if the system crashes.

Bank Transfer Example:
After a successful transfer of ₹1000, the bank server suddenly crashes.

When the system restarts, the transfer remains recorded because the committed transaction was permanently stored.

##### Q4. Write a SQL transaction that does the following atomically: 
#####  1. Insert a new order (order_id=1011, customer_id=102, today's date, 'Pending', 1598.00) 
  2. Insert two order items for that order 
  3. Update the stock_qty of the purchased products 
  4. If any step fails, ROLLBACK the entire transaction. Otherwise, COMMIT. 
Write the complete BEGIN...COMMIT/ROLLBACK block.

In [30]:
print("SQL Transaction Example")
print("""
Example:
Customer with customer_id (102) places new order
Item:
Smart Watch=(product_id=203, qtn=1, unit_price=2999)
Bedsheet Set=(product_id=206, qtn=1, unit_price=1299)
Total_amount=5597.0""")
print()
print()
print("Executing Transaction")
try:
    print("Begin Transaction")
     # Insert order
    print("Insert new order order_id(1011)")
    cursor.execute("""insert into orders values 
                    (1011, 102, '2026-05-30', 'Pending', 5597.00)""")
    print("order placed successfully")
     # Insert order items
    print("Insert into order_items")
    cursor.execute("""insert into order_items values
                    (5016, 1011, 203, 1, 2999.00, 0)""")
    print("Item 1: Smart watch")
    cursor.execute("""insert into order_items values
                    (5017, 1011, 206, 2, 1299.00, 0)""")
    print("  Item 2: Cushion Covers")

     # Update stock
    print(" Update product stock quantities")
    cursor.execute("update products set stock_qty = stock_qty - 1 where product_id = 203")
    print("  Smart Watch stock: -1")
    
    cursor.execute("update products set stock_qty = stock_qty - 2 where product_id = 206")
    print("  Bedsheet Set stock: -2")

    # COMMIT
    print("  COMMIT transaction")
    con.commit()
    print("TRANSACTION SUCCESSFUL")
except Exception as e:
    print(f"{e}")
    print("\nROLLBACK: Undo all changes ")
    con.rollback()
    print(" Transaction rolled back - no changes made")

SQL Transaction Example

Example:
Customer with customer_id (102) places new order
Item:
Smart Watch=(product_id=203, qtn=1, unit_price=2999)
Bedsheet Set=(product_id=206, qtn=1, unit_price=1299)
Total_amount=5597.0


Executing Transaction
Begin Transaction
Insert new order order_id(1011)
UNIQUE constraint failed: orders.order_id

ROLLBACK: Undo all changes
 Transaction rolled back - no changes made

In [36]:
print(" Verification: Updated Stock")
query_stock = """select product_id, product_name, stock_qty 
                 from products where product_id in (203, 206)"""
df_stock = run_query(query_stock)
df_stock

 Verification: Updated Stock

   product_id  product_name  stock_qty
0         203   Smart Watch        150
1         206  Bedsheet Set        300